name: Deploy Frontend

on:
  push:
    branches:
      - release

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 레포지토리 클론
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 설치
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # 3. 의존성 설치 및 빌드
      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      # 4. 빌드 파일 서버로 전송
      - name: Deploy to Nginx server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_PRIVATE_KEY }}
          source: ./dist/
          target: /var/www/html/
